### ISSUE TITLE
Create Stars/Gift Stars

### ISSUE THREAD

**Issue by Beachbob001** [m3taphor/TinyVerse#1]
An option for automatic creation of stars would be great, maybe even an option to gift stars to a defined galaxy.

**Comment by m3taphor** [comment]
Thank you or suggestion, i am gonna push update soon!

**Comment by Imaroubat** [comment]
> Thank you or suggestion, i am gonna push update soon!

when ?

**Comment by m3taphor** [comment]
i will let you know, this update is going to be paid i suppose

**Comment by Imaroubat** [comment]
> i will let you know, this update is going to be paid i suppose

)))
