### ISSUE TITLE
socket error: 407

### ISSUE THREAD

**Issue by For1ndez** [m3taphor/TinyVerse#15]
Hi, do you know what the problem might be? I am using resident ipis with rotation.
![image](https://github.com/user-attachments/assets/17cc035d-6e4a-4e4b-bb0b-d37d7f30b583)

**Comment by m3taphor** [comment]
Proxy error, expired or Credentials are invalid

**Comment by For1ndez** [comment]
Yes, that's the problem, the proxy is working, the script determines the IP address from the pool at startup. I want to use resident APIs with rotation, that is, for example, in my version, the host looks like this: proxy.market.pool:10000

**Comment by For1ndez** [comment]
There's nothing wrong with regular static proxies, but for some reason it gives you an error.
